export const THEME_COLORS = [
  { name: 'Pool Yellow', value: '#FFFF33' },
  { name: 'Pool Red', value: '#FF001C' },
  { name: 'White', value: '#FFFFFF' },
  { name: 'Slate 200', value: '#E2E8F0' },
  { name: 'Red 400', value: '#F87171' },
  { name: 'Red 500', value: '#EF4444' },
  { name: 'Orange 400', value: '#FB923C' },
  { name: 'Orange 500', value: '#F97316' },
  { name: 'Amber 400', value: '#FBBF24' },
  { name: 'Amber 500', value: '#F59E0B' },
  { name: 'Yellow 400', value: '#FACC15' },
  { name: 'Lime 400', value: '#A3E635' },
  { name: 'Emerald 400', value: '#34D399' },
  { name: 'Emerald 500', value: '#10B981' },
  { name: 'Teal 400', value: '#2DD4BF' },
  { name: 'Cyan 400', value: '#22D3EE' },
  { name: 'Sky 400', value: '#38BDF8' },
  { name: 'Blue 400', value: '#60A5FA' },
  { name: 'Blue 500', value: '#3B82F6' },
  { name: 'Indigo 400', value: '#818CF8' },
  { name: 'Violet 400', value: '#A78BFA' },
  { name: 'Purple 400', value: '#C084FC' },
  { name: 'Fuchsia 400', value: '#E879F9' },
  { name: 'Pink 400', value: '#F472B6' },
  { name: 'Rose 400', value: '#FB7185' },
];

export const BACKGROUND_COLORS = [
  { name: 'Black', value: '#000000' },
  { name: 'Slate 900', value: '#0f172a' },
  { name: 'Slate 950', value: '#020617' },
  { name: 'Zinc 900', value: '#18181b' },
  { name: 'Zinc 950', value: '#09090b' },
  { name: 'Neutral 900', value: '#171717' },
  { name: 'Stone 900', value: '#1c1917' },
  { name: 'Red 900', value: '#7f1d1d' },
  { name: 'Red 950', value: '#450a0a' },
  { name: 'Orange 900', value: '#7c2d12' },
  { name: 'Amber 900', value: '#78350f' },
  { name: 'Yellow 900', value: '#713f12' },
  { name: 'Lime 900', value: '#365314' },
  { name: 'Green 900', value: '#14532d' },
  { name: 'Emerald 900', value: '#064e3b' },
  { name: 'Teal 900', value: '#134e4a' },
  { name: 'Cyan 900', value: '#164e63' },
  { name: 'Sky 900', value: '#0c4a6e' },
  { name: 'Blue 900', value: '#1e3a8a' },
  { name: 'Indigo 900', value: '#312e81' },
  { name: 'Violet 900', value: '#4c1d95' },
  { name: 'Purple 900', value: '#581c87' },
  { name: 'Fuchsia 900', value: '#701a75' },
  { name: 'Pink 900', value: '#831843' },
  { name: 'Rose 900', value: '#881337' },
];

export const POOL_BALLS = [
  // REDS
  { number: 3, name: 'Red', value: '#FF0000', image: new URL('./assets/Pool_Balls/red_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/red_poolball_thumb.png', import.meta.url).href },
  { number: 11, name: 'Redish', value: '#F87171', image: new URL('./assets/Pool_Balls/redish_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/redish_poolball_thumb.png', import.meta.url).href },
  { number: 7, name: 'Dark Red', value: '#7F1D1D', image: new URL('./assets/Pool_Balls/red_dark_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/red_dark_poolball_thumb.png', import.meta.url).href },
  // ORANGES
  { number: 16, name: 'Bright Orange', value: '#FF8C00', image: new URL('./assets/Pool_Balls/orange_bright_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/orange_light_poolball_thumb.png', import.meta.url).href },
  { number: 5, name: 'Orange', value: '#FFA500', image: new URL('./assets/Pool_Balls/orange_light_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/orange_light_poolball_thumb.png', import.meta.url).href },
  { number: 13, name: 'Dark Orange', value: '#7C2D12', image: new URL('./assets/Pool_Balls/orange_dark_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/orange_dark_poolball_thumb.png', import.meta.url).href },
  // YELLOWS
  { number: 15, name: 'Bright Yellow', value: '#FFFF00', image: new URL('./assets/Pool_Balls/yellow_bright_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/yellow_poolball_thumb.png', import.meta.url).href },
  { number: 1, name: 'Yellow', value: '#FFD700', image: new URL('./assets/Pool_Balls/yellow_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/yellow_poolball_thumb.png', import.meta.url).href },
  // GREENS
  { number: 18, name: 'Bright Green', value: '#00FF00', image: new URL('./assets/Pool_Balls/green_bright_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/green_poolball_thumb.png', import.meta.url).href },
  { number: 6, name: 'Green', value: '#008000', image: new URL('./assets/Pool_Balls/green_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/green_poolball_thumb.png', import.meta.url).href },
  // BLUES
  { number: 2, name: 'Blue', value: '#0000FF', image: new URL('./assets/Pool_Balls/dark_blue_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/dark_blue_poolball_thumb.png', import.meta.url).href },
  // PURPLES / PINKS
  { number: 10, name: 'Lilac', value: '#D8B4FE', image: new URL('./assets/Pool_Balls/lilac_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/lilac_poolball_thumb.png', import.meta.url).href },
  { number: 4, name: 'Purple', value: '#800080', image: new URL('./assets/Pool_Balls/dark_purple_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/dark_purple_poolball_thumb.png', import.meta.url).href },
  { number: 17, name: 'Bright Pink', value: '#FF69B4', image: new URL('./assets/Pool_Balls/pink_bright_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/pink_poolball_thumb.png', import.meta.url).href },
  { number: 9, name: 'Pink', value: '#F472B6', image: new URL('./assets/Pool_Balls/pink_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/pink_poolball_thumb.png', import.meta.url).href },
  // NEUTRALS
  { number: 12, name: 'White', value: '#FFFFFF', image: new URL('./assets/Pool_Balls/white_poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/white_poolball_thumb.png', import.meta.url).href },
  { number: 14, name: 'Black', value: '#111111', image: new URL('./assets/Pool_Balls/black-Poolball.png', import.meta.url).href, thumbnail: new URL('./assets/Pool_Balls/mini_balls/black-Poolball_thumb.png', import.meta.url).href },
];

export const CLOTH_COLORS = [
  { name: 'Tournament Blue', value: '#2A52BE' },
  { name: 'Tournament Green', value: '#006400' },
  { name: 'English Red', value: '#8B0000' },
  { name: 'Slate Grey', value: '#708090' },
  { name: 'Electric Blue', value: '#00FFFF' },
  { name: 'Tan', value: '#D2B48C' },
  { name: 'Black', value: '#000000' },
  { name: 'Purple Haze', value: '#4B0082' },
];

export const SPEED_CLOTH_COLORS = [
  { name: 'Powder Blue', value: '#B0E0E6' },
  { name: 'Simonis Green', value: '#2E8B57' },
  { name: 'Petrol Blue', value: '#005F6B' },
  { name: 'Shark Grey', value: '#696969' },
  { name: 'Burgundy', value: '#800020' },
  { name: 'Camel', value: '#C19A6B' },
];

export const FULL_SCREEN_BACKDROPS = [
  { name: 'Disabled', value: 'none', image: null, thumbnail: null },
  { name: 'Black', value: 'black', image: new URL('./assets/tables/black_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/black_pool_table_thumb.png', import.meta.url).href },
  { name: 'Blue', value: 'blue', image: new URL('./assets/tables/blue_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/blue_pool_table_thumb.png', import.meta.url).href },
  { name: 'Blue Light', value: 'blue_light', image: new URL('./assets/tables/blue_light_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/blue_light_pool_table_thumb.png', import.meta.url).href },
  { name: 'Green', value: 'green', image: new URL('./assets/tables/green_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/green_pool_table_thumb.png', import.meta.url).href },
  { name: 'Grey Light', value: 'grey_light', image: new URL('./assets/tables/grey_light_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/grey_light_pool_table_thumb.png', import.meta.url).href },
  { name: 'Pink', value: 'pink', image: new URL('./assets/tables/pink_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/pink_pool_table_thumb.png', import.meta.url).href },
  { name: 'Purple', value: 'purple', image: new URL('./assets/tables/purple_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/purple_pool_table_thumb.png', import.meta.url).href },
  { name: 'Red', value: 'red', image: new URL('./assets/tables/red_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/red_pool_table_thumb.png', import.meta.url).href },
  { name: 'Chequer', value: 'chequer', image: new URL('./assets/tables/chequer_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/chequer_pool_table_thumb.png', import.meta.url).href },
  { name: 'England', value: 'england', image: new URL('./assets/tables/england_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/england_pool_table_thumb.png', import.meta.url).href },
  { name: 'France', value: 'france', image: new URL('./assets/tables/frnce_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/frnce_pool_table_thumb.png', import.meta.url).href },
  { name: 'German', value: 'german', image: new URL('./assets/tables/german_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/german_pool_table_thumb.png', import.meta.url).href },
  { name: 'Ireland', value: 'ireland', image: new URL('./assets/tables/ireland_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/ireland_pool_table_thumb.png', import.meta.url).href },
  { name: 'Japan', value: 'japan', image: new URL('./assets/tables/japan_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/japan_pool_table_thumb.png', import.meta.url).href },
  { name: 'Kernow', value: 'kernow', image: new URL('./assets/tables/kernow_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/kernow_pool_table_thumb.png', import.meta.url).href },
  { name: 'Northern Ireland', value: 'northern_ireland', image: new URL('./assets/tables/northern_ireland_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/northern_ireland_pool_table_thumb.png', import.meta.url).href },
  { name: 'Scotland', value: 'scotland', image: new URL('./assets/tables/scot_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/scot_pool_table_thumb.png', import.meta.url).href },
  { name: 'Union', value: 'union', image: new URL('./assets/tables/union_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/union_pool_table_thumb.png', import.meta.url).href },
  { name: 'USA', value: 'usa', image: new URL('./assets/tables/usa_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/usa_pool_table_thumb.png', import.meta.url).href },
  { name: 'Wales', value: 'wales', image: new URL('./assets/tables/wales_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/wales_pool_table_thumb.png', import.meta.url).href },
  { name: 'Magma', value: 'magma', image: new URL('./assets/tables/magma_pool_table.png', import.meta.url).href, thumbnail: new URL('./assets/tables/mini_tables/magma_pool_table_thumb.png', import.meta.url).href },
];
